"use client";

import Link from "next/link";
import {
  IconArrowRight,
  IconFlame,
  IconChartBar,
  IconSearch,
  IconBulb,
  IconCheck,
} from "@tabler/icons-react";
import { motion } from "framer-motion";
import {
  Badge,
  Box,
  Button,
  Container,
  Group,
  Image,
  RingProgress,
  SimpleGrid,
  Stack,
  Text,
  Title,
  ThemeIcon,
  Divider,
} from "@mantine/core";
import { GradientText, FadeInUp } from "../components/animations";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { SectionHeader } from "../components/SectionHeader";
import { SubpageHero } from "../components/SubpageHero";
import { WebsiteCTA } from "../components/WebsiteCTA";
import { getAllCaseStudies, DIAGNOSIS_STATS } from "../data/case-studies";
import classes from "../website.module.css";

function DemandScoreGauge({ score }: { score: number }) {
  const color =
    score >= 80 ? "teal" : score >= 65 ? "yellow" : score >= 50 ? "orange" : "red";

  return (
    <Group gap="sm" align="center">
      <Stack gap={0} align="flex-end">
        <Text size="xs" c="dimmed" fw={600} tt="uppercase" lts={1} ta="right">
          Demand
        </Text>
        <Text size="xs" fw={700} ta="right">
          Score
        </Text>
      </Stack>
      <RingProgress
        size={56}
        thickness={5}
        roundCaps
        sections={[{ value: score, color }]}
        label={
          <Text ta="center" fw={700} size="sm">
            {score}
          </Text>
        }
      />
    </Group>
  );
}

export function CaseStudiesClient() {
  return (
    <Box className={classes.root}>
      <Header />

      {/* Hero */}
      <SubpageHero
        badge={{ text: "Real Companies, Real Data", icon: <IconFlame size={14} /> }}
        title={
          <Box>
            Real Startups. <br />
            <GradientText animate>Unfiltered Truths.</GradientText>
          </Box>
        }
        subtitle="Browse actual diagnoses generated by our system. No fluff, no consultant-speak—just raw data, calculated Demand Scores, and actionable growth strategies."
        minHeight={500}
      />

      {/* Case Study Cards */}
      <Box py={80} id="case-studies">
        <Container size="lg">
          <SimpleGrid cols={{ base: 1, md: 3 }} spacing={30}>
            {getAllCaseStudies().map((study, index) => {
              const verdictColor =
                study.verdict === "GO"
                  ? "teal"
                  : study.verdict === "CONDITIONAL"
                    ? "yellow"
                    : "red";

              return (
                <motion.div
                  key={study.slug}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.15, duration: 0.5 }}
                  style={{ height: "100%" }}
                >
                  <Box className={classes.caseStudyCard}>
                    <Box p="xl" style={{ flex: 1, display: "flex", flexDirection: "column", gap: "var(--mantine-spacing-md)" }}>
                      {/* Header Section */}
                      <Group justify="space-between" align="flex-start" wrap="nowrap">
                        <Stack gap="xs">
                          {study.logo && (
                            <Image
                              src={study.logo}
                              alt={`${study.company} logo`}
                              h={28}
                              w="auto"
                              fit="contain"
                              style={{ alignSelf: "flex-start" }}
                            />
                          )}
                          <Title order={3} size="h4" mt={4}>
                            {study.company}
                          </Title>
                          <Text size="xs" c="dimmed">
                            {study.industry}
                          </Text>
                        </Stack>
                        <DemandScoreGauge score={study.demandScore} />
                      </Group>

                      {/* Badges */}
                      <Group gap={8}>
                        <Badge variant="dot" color={verdictColor} size="sm">
                          {study.verdict === "CONDITIONAL" ? "CONDITIONAL GO" : study.verdict}
                        </Badge>
                        <Badge variant="outline" color="gray" size="sm">
                          {study.stage}
                        </Badge>
                      </Group>

                      <Divider color="var(--website-border)" />

                      {/* Title/Hook */}
                      <Text size="md" fw={600} lh={1.4}>
                        &ldquo;{study.title}&rdquo;
                      </Text>

                      {/* Findings */}
                      <Stack gap={8}>
                        <Text size="xs" fw={700} tt="uppercase" c="dimmed" lts={1}>
                          Key Findings
                        </Text>
                        {study.keyFindings.slice(0, 3).map((finding, i) => (
                          <Group key={i} gap={8} align="flex-start" wrap="nowrap">
                            <ThemeIcon size={6} radius="xl" color="gray" mt={7} />
                            <Text size="sm" c="dimmed" lh={1.4}>
                              {finding}
                            </Text>
                          </Group>
                        ))}
                      </Stack>
                    </Box>

                    {/* The One Thing - Highlighted at bottom */}
                    <Box
                      p="md"
                      m="md"
                      className={classes.oneThingBox}
                      mt="auto"
                    >
                      <Group gap={6} mb={4}>
                        <IconBulb size={14} color="var(--website-primary)" />
                        <Text size="xs" fw={700} tt="uppercase" c="primary.4">
                          The One Thing
                        </Text>
                      </Group>
                      <Text size="sm" lh={1.5} fw={500}>
                        {study.theOneThing}
                      </Text>
                    </Box>

                    {/* Footer / CTA */}
                    <Box p="md" pt={0}>
                      <Button
                        component={Link}
                        href={`/case-studies/${study.slug}`}
                        variant="light"
                        color="gray"
                        fullWidth
                        rightSection={<IconArrowRight size={16} />}
                        className={classes.outlineButton}
                      >
                        Read Case Study
                      </Button>
                    </Box>
                  </Box>
                </motion.div>
              );
            })}
          </SimpleGrid>
        </Container>
      </Box>

      {/* Visual Stats Section */}
      <Box py={100} style={{ position: "relative", overflow: "hidden" }}>
        {/* Background blobs */}
        <div className={classes.floatingOrb3} style={{ top: "20%", left: "-10%", opacity: 0.5 }} />

        <Container size="lg" style={{ position: "relative", zIndex: 1 }}>
          <SectionHeader
            title="The Depth of"
            highlightedText="Analysis"
            subtitle="Most consultants just give you an opinion. We give you widespread intelligence gathered from thousands of data points."
          />

          <SimpleGrid cols={{ base: 2, md: 4 }} spacing="xl" mt={60}>
            {DIAGNOSIS_STATS.map((stat, index) => (
              <FadeInUp key={stat.label} delay={index * 0.1}>
                <Box className={classes.statCard}>
                  <Text
                    size="3.5rem"
                    fw={800}
                    variant="gradient"
                    gradient={{ from: "cyan", to: "blue" }}
                    lh={1}
                    mb="xs"
                  >
                    {stat.value}
                  </Text>
                  <Text size="sm" fw={600} c="dimmed" tt="uppercase" lts={1}>
                    {stat.label}
                  </Text>
                </Box>
              </FadeInUp>
            ))}
          </SimpleGrid>
        </Container>
      </Box>

      {/* Process / How it Works */}
      <Box py={100} style={{ background: "var(--website-muted-bg)" }}>
        <Container size="lg">
          <SectionHeader
            title="From URL to"
            highlightedText="Strategy"
            subtitle="We don't need access to your analytics. We analyze your business from the outside-in, exactly how your customers see it."
          />

          <SimpleGrid cols={{ base: 1, md: 3 }} spacing={30} mt={60}>
            {[
              {
                step: "01",
                title: "Ingest",
                desc: "We consume every public signal about your business, from your landing page copy to your competitors' ad spend.",
                icon: <IconSearch size={24} />,
              },
              {
                step: "02",
                title: "Analyze",
                desc: "Our system cross-references market intent data with your value proposition to identify gaps and opportunities.",
                icon: <IconChartBar size={24} />,
              },
              {
                step: "03",
                title: "Unlock",
                desc: "You receive a definitive Demand Score and a prioritized roadmap of the highest-leverage actions you can take today.",
                icon: <IconCheck size={24} />,
              },
            ].map((item, i) => (
              <FadeInUp key={item.step} delay={i * 0.2}>
                <Box className={classes.processCard}>
                  <Text className={classes.processNumber}>{item.step}</Text>
                  <Stack gap="md" style={{ position: "relative", zIndex: 2 }}>
                    <ThemeIcon size={48} radius="md" variant="light" color="cyan">
                      {item.icon}
                    </ThemeIcon>
                    <Title order={3} size="h3">{item.title}</Title>
                    <Text c="dimmed" lh={1.6}>
                      {item.desc}
                    </Text>
                  </Stack>
                </Box>
              </FadeInUp>
            ))}
          </SimpleGrid>
        </Container>
      </Box>

      {/* CTA */}
      <WebsiteCTA
        title="Get Your Diagnosis"
        subtitle="Stop guessing. Get real data on your market demand and validation score."
        primaryAction={{ label: "Get Diagnosed Now", href: "/diagnosis" }}
        secondaryAction={{ label: "See Methodology", href: "/docs" }}
      />

      <Footer />
    </Box>
  );
}
